### PR TITLE
Include `period_start` in request doc output

### LINKED ISSUE #69: Inclusion of 'period_start' date to the daily export of the CyHy Requests collection
# Summary #

Insights is requesting the inclusion of the ‘period_start’ date to the daily export of the CyHy Requests collection for ingest into their Analytic Environment (AE). 

## Motivation and context ##

Their analysts will use this information in development of cyber-risk summary visualizations. This ticket has been assigned a "high" priority but I'm not aware of this being in a ranked list. I would suggest if the LOE is greater than XS (i.e. 1 day) let me know and I'll suggest the PM team align this change vs. other priorities.

## Implementation notes ##

The CD team confirmed they have already made the changes on the ingest side. They should be able to start ingesting this new field at any time. They have requested we either start with a test case or give them notice of the date/time we plan to start sending this data to ensure monitoring of any potential issues. Please let me know if I can help track down any questions.

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR adds the `period_start` field into the request document output.

## 💭 Motivation and context ##

This field was requested; resolves https://github.com/cisagov/cyhy-system/issues/69.

It's important to remember that `period_start` indicates the most-recent start time of scanning for an organization.  It may be the initial start of scanning, but if an organization has ever paused and resumed their scanning, `period_start` will show the time when scanning was most-recently resumed, not when it was initially started.  Also, while scanning is paused for an organization, `period_start` will be set to a date far in the future (the year 9999).

## 🧪 Testing ##

I manually made this change in a test environment and ran `cyhy-data-extract.py`.  I confirmed that the `period_start` field was indeed included in the requests JSON file as intended.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All new and existing tests pass.

## ✅ Post-merge checklist ##

- [x] Coordinate with downstream stakeholders on Production deployment date.
- [x] Deploy updated code to Production.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Approved, but it looks like Python 2.7 support might need to be dropped for this project.  [cisagov/mongo-db-from-config](https://github.com/cisagov/mongo-db-from-config) only supports Python 3.

**Comment by dav3r** [comment]
> Approved, but it looks like Python 2.7 support might need to be dropped for this project. [cisagov/mongo-db-from-config](https://github.com/cisagov/mongo-db-from-config) only supports Python 3.

I know you'll be shocked by this @jsf9k, but you have that change pending in #43. 😄

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Comment by dav3r** [comment]
@jsf9k and @mcdonnnj - Are you ok with me temporarily making the 2.7 tests non-required in order to merge this PR so that it is not held up waiting for #43?

**Pull request merged**
