### PR TITLE
Capture past 26 hours of data instead of 24 in `cyhy-data-extract.py`

### LINKED ISSUE #46: Daily run of `cyhy-data-extract.py` can miss some data
# 🐛 Summary #

When `cyhy-data-extract.py` is run daily, in certain situations, some data will never be exported because it arrives in the database after the script has started to run.

## To reproduce ##

1. Run `cyhy-data-extract.py` at midnight daily.
1. Observe that some data may be timestamped before midnight, but not saved to the database until after midnight.  That data will not be included in the daily extract. 

## Expected behavior ##

All modified data in the database should be exported in a daily extract.

## Additional context ##

It is possible for CyHy data to flow into the database after midnight UTC (when our export script starts) and that data can contain timestamps prior to midnight, since those timestamps (e.g. port_scan timestamps) are based on their scan time, not the time that they are written to the DB.

Our proposed solution involves making the export script capture the previous **26** hours of data instead of the previous **24** hours of data.  This would allow us to capture the missing data in a the next daily run of the script.  This would also mean that there will be some amount of duplicated data appearing in consecutive outputs from the script.

Note regarding solutions: we cannot simply start the export script an hour or two later because the data in CyHy is always changing and that would result in an increased risk of data being overwritten during that extra time (imagine a ticket that was updated at 12:05pm on the 16th, then gets updated again at 12:05am on the 17th; it's latest timestamp would be on the 17th and thus it wouldn't be included in the daily export for the 16th - that is the situation we attempt to minimize by starting our script at midnight).

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR changes `cyhy-data-extract.py` so that it captures the previous 26 hours of data instead of 24 hours.

## 💭 Motivation and context ##

We have seen cases where data was scanned 1 hour prior to the start of the script, yet it was not saved to the database until after the script started, so it was excluded from the daily extract files.  We chose 2 extra hours just to be safe.  Although this means consecutive daily extracts can have some duplicated data, that is preferable to missing data.

Resolves #46.

Note that this PR is blocked by #43.  Once that PR is merged, this PR should pass all tests.

## 🧪 Testing ##

This change will be manually applied in Production today- the true test will be when the daily script runs tonight.  If anything goes wrong, we will deal with it.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Nice comment.  Is there an issue to link to?

**Comment by dav3r** [comment]
> Nice comment. Is there an issue to link to?

There is no issue for this yet.  I will write one up.

**Comment by jsf9k** [comment]
> > Nice comment. Is there an issue to link to?
> 
> There is no issue for this yet. I will write one up.

Thanks.  My thought was that this is a big enough deal that it might be worthwhile making it searchable in multiple different ways.  I'm sure in the future we will wonder how we got here.

**Comment by dav3r** [comment]
> > > Nice comment. Is there an issue to link to?
> > 
> > 
> > There is no issue for this yet. I will write one up.
> 
> Thanks. My thought was that this is a big enough deal that it might be worthwhile making it searchable in multiple different ways. I'm sure in the future we will wonder how we got here.

This issue has been documented in #46.

**Comment by mcdonnnj** [comment]
@dav3r Would you please rebase this on `develop` now that #43 has been merged?

**Comment by dav3r** [comment]
> @dav3r Would you please rebase this on `develop` now that #43 has been merged?

@mcdonnnj Done. 👍

**Review by mcdonnnj — APPROVED** [review]
:shipit:

**Review by jsf9k — APPROVED** [review]

**Pull request merged**
