### PR TITLE
Change tickets query to include newly-created tickets

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR modifies the CyHy tickets query to include new tickets **opened** during the specified time period, in addition to those modified during the time period.

> [!NOTE]
> Since this repo has not yet been re-skeletonized (see #48) and is not yet using lineage, I added the following commits to get it to successfully pass our linting checks:
> * e5de9adc6489f67598ad3903e1b895984f63542d
> * 6f5c9457cd3f708ded99e0be304ab293f916efe4
> * 1128380858f6772658b51655bfae168b4d886e60
> * 7101643774c8b86b7afc14155f825d3975c42d59
> * d41517e8e077f6337210059357b80999678718ab

## 💭 Motivation and context ##

Before this change, it was possible for a ticket to be created within the time period, but modified shortly after the end of the time period, and thus would not be included in the output.  This change corrects that situation, which was not desired.

Our analysts noticed in Production that a new ticket was missing from the daily extract, which prompted this change.

## 🧪 Testing ##

To test this change, I made a modified version of `aws_jobs/cyhy-data-extract.py` that only ran the old tickets query and the new tickets query and provided a list of tickets that were retrieved by the new query, but not the old one.  I then spot-checked a bunch of those tickets to ensure that they looked as expected (i.e. the ticket was created during the time period, but it's `last_modified` timestamp was after the time period).  All of the tickets I checked successfully met that criteria, so I believe this change is correctly implemented.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

## ✅ Post-merge checklist ##

- [x] Deploy this change to Production

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
A simple solution to a thorny problem!

**Comment by jsf9k** [comment]
I think this PR requires some of the changes from cisagov/skeleton-python-library#124 to pass the linter checks.

**Comment by dav3r** [comment]
> I think this PR requires some of the changes from [cisagov/skeleton-python-library#124](https://github.com/cisagov/skeleton-python-library/pull/124) to pass the linter checks.

Yup, working on it (I updated the PR description above to mention this).

**Comment by dav3r** [comment]
> > I think this PR requires some of the changes from [cisagov/skeleton-python-library#124](https://github.com/cisagov/skeleton-python-library/pull/124) to pass the linter checks.
> 
> Yup, working on it (I updated the PR description above to mention this).

Linting now passes.  @jsf9k, please take another quick look just to make sure all is well.

**Review by jsf9k — APPROVED** [review]
_Approval intensifies!!!_

**Review by jasonodoom — APPROVED** [review]

**Review by mcdonnnj — APPROVED** [review]
I'm not sure this will solve the reported issue but there should be no harm in adjusting the query in this way.

**Comment by dav3r** [comment]
I manually deployed the updated `cyhy-data-extract.py` file to production so that we don't have to do a full redeployment of the database instance.  I will review the logs tomorrow morning to look for any unexpected errors in the daily extract process.

**Pull request merged**
